Code is not tidy at line 1, column 1.  See page 33 of PBP.  (Severity: 1)
Magic punctuation variable $! used at line 99, column 77.  See page 79 of PBP.  (Severity: 2)
Magic punctuation variable $! used in interpolated string at line 105, column 16.  See page 79 of PBP.  (Severity: 2)
Reused variable name in lexical scope: $unused at line 185, column 9.  Invent unique variable names.  (Severity: 3)
Builtin function called with parentheses at line 185, column 35.  See page 13 of PBP.  (Severity: 1)
Quotes used with a noisy string at line 185, column 48.  See page 53 of PBP.  (Severity: 2)
"die" used instead of "croak" at line 187, column 16.  See page 283 of PBP.  (Severity: 3)
Mixed high and low-precedence booleans at line 191, column 13.  See page 70 of PBP.  (Severity: 4)
Found "\N{SPACE}" at the end of the line at line 196, column 1.  Don't use whitespace at the end of lines.  (Severity: 1)
Subroutine "joining" does not end with "return" at line 202, column 1.  See page 197 of PBP.  (Severity: 4)
Subroutine "nchange" does not end with "return" at line 221, column 1.  See page 197 of PBP.  (Severity: 4)
Builtin function called with parentheses at line 224, column 17.  See page 13 of PBP.  (Severity: 1)
Too many arguments at line 236, column 1.  See page 182 of PBP.  (Severity: 3)
Subroutine "process_info" does not end with "return" at line 236, column 1.  See page 197 of PBP.  (Severity: 4)
25 is not one of the allowed literal values (0, 1, 2). Use the Readonly or Const::Fast module or the "constant" pragma instead at line 238, column 27.  Unnamed numeric literals make code less maintainable.  (Severity: 2)
Magic punctuation variable $! used in interpolated string at line 244, column 20.  See page 79 of PBP.  (Severity: 2)
Magic punctuation variable $! used in interpolated string at line 249, column 20.  See page 79 of PBP.  (Severity: 2)
Close filehandles as soon as possible after opening them at line 251, column 9.  See page 209 of PBP.  (Severity: 4)
Magic punctuation variable $! used in interpolated string at line 252, column 20.  See page 79 of PBP.  (Severity: 2)
"grep" used in boolean context at line 256, column 14.  See pages 71,72 of PBP.  (Severity: 2)
Expression form of "grep" at line 256, column 14.  See page 169 of PBP.  (Severity: 4)
Builtin function called with parentheses at line 256, column 14.  See page 13 of PBP.  (Severity: 1)
File handle for "print" or "printf" is not braced at line 257, column 13.  See page 217 of PBP.  (Severity: 1)
Return value of flagged function ignored - print at line 257, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Postfix control "if" used at line 258, column 56.  See pages 93,94 of PBP.  (Severity: 2)
Postfix control "if" used at line 260, column 56.  See pages 93,94 of PBP.  (Severity: 2)
Magic punctuation variable $! used in interpolated string at line 264, column 20.  See page 79 of PBP.  (Severity: 2)
Builtin function called with parentheses at line 267, column 13.  See page 13 of PBP.  (Severity: 1)
Return value of "open" ignored at line 267, column 13.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 267, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Reused variable name in lexical scope: @list at line 268, column 13.  Invent unique variable names.  (Severity: 3)
Builtin function called with parentheses at line 269, column 13.  See page 13 of PBP.  (Severity: 1)
Return value of "close" ignored at line 269, column 13.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 269, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 271, column 13.  See page 13 of PBP.  (Severity: 1)
Return value of "open" ignored at line 271, column 13.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 271, column 13.  See pages 208,278 of PBP.  (Severity: 1)
File handle for "print" or "printf" is not braced at line 272, column 13.  See page 217 of PBP.  (Severity: 1)
Return value of flagged function ignored - print at line 272, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 273, column 13.  See page 13 of PBP.  (Severity: 1)
Return value of "close" ignored at line 273, column 13.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 273, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 282, column 14.  See page 13 of PBP.  (Severity: 1)
"die" used instead of "croak" at line 282, column 14.  See page 283 of PBP.  (Severity: 3)
Literal line breaks in a string at line 288, column 17.  See pages 60,61 of PBP.  (Severity: 3)
Put a trailing comma at last of a list ending with a newline at line 293, column 46.  (no explanation).  (Severity: 2)
"warn" used instead of "carp" at line 294, column 18.  See page 283 of PBP.  (Severity: 3)
Magic punctuation variable $! used in interpolated string at line 294, column 23.  See page 79 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 301, column 27.  (no explanation).  (Severity: 2)
"warn" used instead of "carp" at line 302, column 18.  See page 283 of PBP.  (Severity: 3)
Magic punctuation variable $! used in interpolated string at line 302, column 23.  See page 79 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 305, column 97.  (no explanation).  (Severity: 2)
Subroutine "track" with high complexity score (30) at line 323, column 1.  Consider refactoring.  (Severity: 3)
Always unpack @_ first at line 323, column 1.  See page 178 of PBP.  (Severity: 4)
Builtin function called with parentheses at line 326, column 5.  See page 13 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 327, column 15.  See page 13 of PBP.  (Severity: 1)
return called with no arguments at line 334, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 334, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 339, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 339, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 344, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 344, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 349, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 349, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
List declaration without trailing comma at line 353, column 21.  See page 17 of PBP.  (Severity: 1)
String *may* require interpolation at line 354, column 22.  See page 51 of PBP.  (Severity: 1)
String *may* require interpolation at line 354, column 53.  See page 51 of PBP.  (Severity: 1)
Cascading if-elsif chain at line 362, column 5.  See pages 117,118 of PBP.  (Severity: 3)
Return value of "open" ignored at line 366, column 13.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 366, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Return value of "close" ignored at line 368, column 13.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 368, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Put a trailing comma at last of a list ending with a newline at line 379, column 81.  (no explanation).  (Severity: 2)
return called with no arguments at line 382, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 382, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 387, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 387, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 390, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 390, column 9.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
Regular expression without "/s" flag at line 393, column 19.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 393, column 19.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 393, column 19.  See page 237 of PBP.  (Severity: 2)
Useless interpolation of literal string at line 395, column 23.  See page 51 of PBP.  (Severity: 1)
Return value of "open" ignored at line 396, column 13.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 396, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Return value of "close" ignored at line 398, column 13.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 398, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 401, column 17.  See page 13 of PBP.  (Severity: 1)
Cascading if-elsif chain at line 404, column 17.  See pages 117,118 of PBP.  (Severity: 3)
Regular expression without "/s" flag at line 405, column 39.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 405, column 39.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 405, column 39.  See page 237 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 407, column 103.  (no explanation).  (Severity: 2)
Regular expression without "/s" flag at line 412, column 39.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 412, column 39.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 412, column 39.  See page 237 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 414, column 103.  (no explanation).  (Severity: 2)
Regular expression without "/s" flag at line 419, column 40.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 419, column 40.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 419, column 40.  See page 237 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 421, column 104.  (no explanation).  (Severity: 2)
Regular expression without "/s" flag at line 426, column 34.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 426, column 34.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 426, column 34.  See page 237 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 428, column 98.  (no explanation).  (Severity: 2)
Useless interpolation of literal string at line 433, column 34.  See page 51 of PBP.  (Severity: 1)
Use character classes for literal metachars instead of escapes at line 439, column 26.  See page 247 of PBP.  (Severity: 1)
Regular expression without "/s" flag at line 439, column 26.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 439, column 26.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 439, column 26.  See page 237 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 442, column 138.  (no explanation).  (Severity: 2)
Always unpack @_ first at line 459, column 1.  See page 178 of PBP.  (Severity: 4)
"grep" used in void context at line 461, column 5.  Use a "for" loop instead.  (Severity: 3)
Expression form of "grep" at line 461, column 5.  See page 169 of PBP.  (Severity: 4)
Put a trailing comma at last of a list ending with a newline at line 471, column 105.  (no explanation).  (Severity: 2)
Builtin function called with parentheses at line 475, column 13.  See page 13 of PBP.  (Severity: 1)
Return value of "open" ignored at line 475, column 13.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 475, column 13.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 477, column 13.  See page 13 of PBP.  (Severity: 1)
Return value of "close" ignored at line 477, column 13.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 477, column 13.  See pages 208,278 of PBP.  (Severity: 1)
String delimiter used with "split" at line 479, column 29.  Express it as a regex instead.  (Severity: 2)
Builtin function called with parentheses at line 479, column 29.  See page 13 of PBP.  (Severity: 1)
Quotes used with a noisy string at line 479, column 36.  See page 53 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 484, column 27.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 484, column 27.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 484, column 27.  See page 237 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 485, column 27.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 485, column 27.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 485, column 27.  See page 237 of PBP.  (Severity: 2)
"grep" used in boolean context at line 487, column 18.  See pages 71,72 of PBP.  (Severity: 2)
Expression form of "grep" at line 487, column 18.  See page 169 of PBP.  (Severity: 4)
Builtin function called with parentheses at line 487, column 18.  See page 13 of PBP.  (Severity: 1)
Postfix control "if" used at line 495, column 59.  See pages 93,94 of PBP.  (Severity: 2)
Always unpack @_ first at line 503, column 1.  See page 178 of PBP.  (Severity: 4)
return called with no arguments at line 505, column 5.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 505, column 5.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
Regular expression without "/s" flag at line 507, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 507, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 507, column 24.  See page 237 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 508, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 508, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 508, column 24.  See page 237 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 509, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 509, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 509, column 24.  See page 237 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 510, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 510, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 510, column 24.  See page 237 of PBP.  (Severity: 2)
Always unpack @_ first at line 514, column 1.  See page 178 of PBP.  (Severity: 4)
return called with no arguments at line 516, column 5.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 516, column 5.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
Regular expression without "/s" flag at line 518, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 518, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 518, column 24.  See page 237 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 519, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 519, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 519, column 24.  See page 237 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 520, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 520, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 520, column 24.  See page 237 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 521, column 24.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 521, column 24.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 521, column 24.  See page 237 of PBP.  (Severity: 2)
Always unpack @_ first at line 525, column 1.  See page 178 of PBP.  (Severity: 4)
return called with no arguments at line 527, column 5.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
return called with no arguments at line 527, column 5.  return with no arguments may return either undef or an empty list depending on context. This can be surprising for the same reason as other context-sensitive returns. Return undef or the empty list explicitly.  (Severity: 1)
Quotes used with a noisy string at line 530, column 9.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 531, column 9.  See page 53 of PBP.  (Severity: 2)
String *may* require interpolation at line 531, column 9.  See page 51 of PBP.  (Severity: 1)
Quotes used with a noisy string at line 532, column 9.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 532, column 17.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 533, column 9.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 533, column 17.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 534, column 17.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 535, column 17.  See page 53 of PBP.  (Severity: 2)
String *may* require interpolation at line 535, column 17.  See page 51 of PBP.  (Severity: 1)
Quotes used with a noisy string at line 536, column 9.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 536, column 17.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 537, column 9.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 537, column 17.  See page 53 of PBP.  (Severity: 2)
Found "\N{SPACE}" at the end of the line at line 539, column 1.  Don't use whitespace at the end of lines.  (Severity: 1)
C-style "for" loop used at line 540, column 9.  See page 100 of PBP.  (Severity: 2)
Found "\N{SPACE}" at the end of the line at line 546, column 1.  Don't use whitespace at the end of lines.  (Severity: 1)
Builtin function called with parentheses at line 547, column 12.  See page 13 of PBP.  (Severity: 1)
Quotes used with a string containing no non-whitespace characters at line 547, column 17.  See page 53 of PBP.  (Severity: 2)
Subroutine "importAKA" is not all lower case or all upper case at line 551, column 1.  See pages 45,46 of PBP.  (Severity: 1)
Always unpack @_ first at line 551, column 1.  See page 178 of PBP.  (Severity: 4)
Subroutine "importAKA" does not end with "return" at line 551, column 1.  See page 197 of PBP.  (Severity: 4)
Builtin function called with parentheses at line 554, column 9.  See page 13 of PBP.  (Severity: 1)
Return value of "open" ignored at line 554, column 9.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 554, column 9.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 556, column 9.  See page 13 of PBP.  (Severity: 1)
Return value of "close" ignored at line 556, column 9.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 556, column 9.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 560, column 13.  See page 13 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 565, column 33.  See page 13 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 567, column 21.  See page 13 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 579, column 20.  See page 13 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 580, column 9.  See page 13 of PBP.  (Severity: 1)
Return value of "open" ignored at line 580, column 9.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 580, column 9.  See pages 208,278 of PBP.  (Severity: 1)
Regular expression without "/s" flag at line 583, column 25.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 583, column 25.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 583, column 25.  See page 237 of PBP.  (Severity: 2)
File handle for "print" or "printf" is not braced at line 584, column 17.  See page 217 of PBP.  (Severity: 1)
Return value of flagged function ignored - print at line 584, column 17.  See pages 208,278 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 588, column 9.  See page 13 of PBP.  (Severity: 1)
Return value of "close" ignored at line 588, column 9.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 588, column 9.  See pages 208,278 of PBP.  (Severity: 1)
Subroutine "sql_init" does not end with "return" at line 593, column 1.  See page 197 of PBP.  (Severity: 4)
Literal line breaks in a string at line 595, column 29.  See pages 60,61 of PBP.  (Severity: 3)
Backtick operator used at line 624, column 11.  Use IPC::Open3 instead.  (Severity: 3)
Put a trailing comma at last of a list ending with a newline at line 624, column 80.  (no explanation).  (Severity: 2)
Regular expression without "/s" flag at line 627, column 19.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/m" flag at line 627, column 19.  See page 237 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 629, column 88.  (no explanation).  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 632, column 85.  (no explanation).  (Severity: 2)
Backtick operator used at line 636, column 25.  Use IPC::Open3 instead.  (Severity: 3)
Useless interpolation of literal string at line 637, column 18.  See page 51 of PBP.  (Severity: 1)
Postfix control "if" used at line 637, column 29.  See pages 93,94 of PBP.  (Severity: 2)
3 is not one of the allowed literal values (0, 1, 2). Use the Readonly or Const::Fast module or the "constant" pragma instead at line 637, column 48.  Unnamed numeric literals make code less maintainable.  (Severity: 2)
Backtick operator used at line 640, column 25.  Use IPC::Open3 instead.  (Severity: 3)
Useless interpolation of literal string at line 641, column 18.  See page 51 of PBP.  (Severity: 1)
Postfix control "if" used at line 641, column 29.  See pages 93,94 of PBP.  (Severity: 2)
3 is not one of the allowed literal values (0, 1, 2). Use the Readonly or Const::Fast module or the "constant" pragma instead at line 641, column 48.  Unnamed numeric literals make code less maintainable.  (Severity: 2)
Backtick operator used at line 645, column 22.  Use IPC::Open3 instead.  (Severity: 3)
Put a trailing comma at last of a list ending with a newline at line 648, column 37.  (no explanation).  (Severity: 2)
Useless interpolation of literal string at line 650, column 18.  See page 51 of PBP.  (Severity: 1)
Postfix control "if" used at line 650, column 29.  See pages 93,94 of PBP.  (Severity: 2)
3 is not one of the allowed literal values (0, 1, 2). Use the Readonly or Const::Fast module or the "constant" pragma instead at line 650, column 48.  Unnamed numeric literals make code less maintainable.  (Severity: 2)
Magic punctuation variable $! used in interpolated string at line 655, column 14.  See page 79 of PBP.  (Severity: 2)
Always unpack @_ first at line 661, column 1.  See page 178 of PBP.  (Severity: 4)
Subroutine "track_options" does not end with "return" at line 661, column 1.  See page 197 of PBP.  (Severity: 4)
Regular expression without "/s" flag at line 663, column 15.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/m" flag at line 663, column 15.  See page 237 of PBP.  (Severity: 2)
Builtin function called with parentheses at line 676, column 21.  See page 13 of PBP.  (Severity: 1)
Put a trailing comma at last of a list ending with a newline at line 680, column 108.  (no explanation).  (Severity: 2)
Regular expression without "/s" flag at line 684, column 48.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 684, column 48.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 684, column 48.  See page 237 of PBP.  (Severity: 2)
Useless interpolation of literal string at line 701, column 13.  See page 51 of PBP.  (Severity: 1)
Useless interpolation of literal string at line 701, column 54.  See page 51 of PBP.  (Severity: 1)
Useless interpolation of literal string at line 701, column 66.  See page 51 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 734, column 44.  See page 13 of PBP.  (Severity: 1)
Subroutine "raw_to_sql" does not end with "return" at line 738, column 1.  See page 197 of PBP.  (Severity: 4)
Return value of "open" ignored at line 739, column 5.  Check the return value of "open" for success.  (Severity: 3)
Return value of flagged function ignored - open at line 739, column 5.  See pages 208,278 of PBP.  (Severity: 1)
Return value of "close" ignored at line 741, column 5.  Check the return value of "close" for success.  (Severity: 2)
Return value of flagged function ignored - close at line 741, column 5.  See pages 208,278 of PBP.  (Severity: 1)
Put a trailing comma at last of a list ending with a newline at line 744, column 196.  (no explanation).  (Severity: 2)
"warn" used instead of "carp" at line 745, column 10.  See page 283 of PBP.  (Severity: 3)
Magic punctuation variable $! used in interpolated string at line 745, column 15.  See page 79 of PBP.  (Severity: 2)
String delimiter used with "split" at line 748, column 38.  Express it as a regex instead.  (Severity: 2)
Builtin function called with parentheses at line 748, column 38.  See page 13 of PBP.  (Severity: 1)
Quotes used with a noisy string at line 748, column 45.  See page 53 of PBP.  (Severity: 2)
Quotes used with a string containing no non-whitespace characters at line 753, column 25.  See page 53 of PBP.  (Severity: 2)
Quotes used with a string containing no non-whitespace characters at line 754, column 25.  See page 53 of PBP.  (Severity: 2)
"warn" used instead of "carp" at line 762, column 14.  See page 283 of PBP.  (Severity: 3)
Magic punctuation variable $! used in interpolated string at line 762, column 19.  See page 79 of PBP.  (Severity: 2)
Subroutine "process_chans" does not end with "return" at line 766, column 1.  See page 197 of PBP.  (Severity: 4)
Regular expression without "/s" flag at line 769, column 19.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 769, column 19.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 769, column 19.  See page 237 of PBP.  (Severity: 2)
Builtin function called with parentheses at line 770, column 25.  See page 13 of PBP.  (Severity: 1)
Builtin function called with parentheses at line 772, column 25.  See page 13 of PBP.  (Severity: 1)
Quotes used with a string containing no non-whitespace characters at line 772, column 32.  See page 53 of PBP.  (Severity: 2)
Regular expression without "/s" flag at line 777, column 26.  See pages 240,241 of PBP.  (Severity: 2)
Regular expression without "/x" flag at line 777, column 26.  See page 236 of PBP.  (Severity: 3)
Regular expression without "/m" flag at line 777, column 26.  See page 237 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 784, column 95.  (no explanation).  (Severity: 2)
Builtin function called with parentheses at line 785, column 18.  See page 13 of PBP.  (Severity: 1)
"die" used instead of "croak" at line 785, column 18.  See page 283 of PBP.  (Severity: 3)
Put a trailing comma at last of a list ending with a newline at line 791, column 110.  (no explanation).  (Severity: 2)
Subroutine "notice" does not end with "return" at line 800, column 1.  See page 197 of PBP.  (Severity: 4)
Postfix control "if" used at line 821, column 21.  See pages 93,94 of PBP.  (Severity: 2)
Found "\N{SPACE}" at the end of the line at line 824, column 20.  Don't use whitespace at the end of lines.  (Severity: 1)
Split long regexps into smaller qr// chunks at line 825, column 9.  See page 261 of PBP.  (Severity: 3)
Only use a capturing group if you plan to use the captured value at line 825, column 9.  See page 252 of PBP.  (Severity: 3)
Magic punctuation variable $+ used at line 827, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 827, column 24.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 828, column 21.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 828, column 34.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 829, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a string containing no non-whitespace characters at line 829, column 23.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 830, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 830, column 24.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 831, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 831, column 23.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 832, column 13.  See page 79 of PBP.  (Severity: 2)
Put a trailing comma at last of a list ending with a newline at line 834, column 95.  (no explanation).  (Severity: 2)
Split long regexps into smaller qr// chunks at line 840, column 9.  See page 261 of PBP.  (Severity: 3)
Only use a capturing group if you plan to use the captured value at line 840, column 9.  See page 252 of PBP.  (Severity: 3)
Magic punctuation variable $+ used at line 842, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 842, column 24.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 843, column 21.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 843, column 34.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 844, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a string containing no non-whitespace characters at line 844, column 23.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 845, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 845, column 24.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 846, column 13.  See page 79 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 846, column 23.  See page 53 of PBP.  (Severity: 2)
Magic punctuation variable $+ used at line 847, column 13.  See page 79 of PBP.  (Severity: 2)
Useless interpolation of literal string at line 850, column 18.  See page 51 of PBP.  (Severity: 1)
Literal line breaks in a string at line 854, column 12.  See pages 60,61 of PBP.  (Severity: 3)
